name: Build
on: [ push ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Add JavaFX to PATH
        run: |
          setx PATH "%PATH%;C:\Program Files (x86)\JavaFX\lib"

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Test jpackage
        run: |
          jpackage --version