name: Build and Release
on: [ push ]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Get Current Version
        id: version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $CURRENT_VERSION"
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Check Against Latest Release
        id: version_check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get latest release version from GitHub API
          RESPONSE=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest")

          if echo "$RESPONSE" | grep -q "Not Found"; then
            LATEST_VERSION="0.0.0"
          else
            LATEST_VERSION=$(echo "$RESPONSE" | jq -r '.tag_name | sub("^v"; "")')
          fi

          echo "Latest release version: $LATEST_VERSION"
          echo "Current version: ${{ steps.version.outputs.version }}"

          if [ "${{ steps.version.outputs.version }}" != "$LATEST_VERSION" ]; then
            echo "::notice::New version detected! Triggering release"
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "::notice::No version change detected"
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Package and Create Installer
        if: steps.version_check.outputs.should_release == 'true'
        run: ./mvnw clean package

      - name: Create Release
        if: steps.version_check.outputs.should_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: ZChess v${{ steps.version.outputs.version }}
          body: |
            Automated release for version ${{ steps.version.outputs.version }}
            - Built with Java 17
            - Installer generated using jpackage
          files: |
            target/dist/ZChess-${{ steps.version.outputs.version }}.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}