name: Build
on: [ push ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch the current and previous commit

      - name: Check for Version Changes
        id: version_check
        run: |
          # Extract the current version from pom.xml
          CURR_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)

          # Extract the previous version from the previous commit's pom.xml
          PREV_VERSION=$(git show HEAD~1:pom.xml | xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" -)

          echo "Current Version: $CURR_VERSION"
          echo "Previous Version: $PREV_VERSION"

          # Compare versions
          if [ "$CURR_VERSION" != "$PREV_VERSION" ]; then
            echo "New version detected: $CURR_VERSION"
            echo "::set-output name=should_build::true"
          else
            echo "No new version detected."
            echo "::set-output name=should_build::false"
          fi
        shell: bash

      - name: Build with Maven
        if: steps.version_check.outputs.should_build == 'true'
        run: ./mvnw clean package

      - name: Test jpackage
        if: steps.version_check.outputs.should_build == 'true'
        run: |
          jpackage --version
